version: '3.2'
services:
  db:
    container_name: social_network
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"

  user:
    container_name: db
    build: .
    environment:
      - DB_HOST=social_network
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: