version: '3.2'
services:
  db:
    container_name: social_network
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: on-failure
    volumes:
      - mongodb_data:/var/lib/mongodb/data
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  cache_sn:
    container_name: cache_sn
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - sn_cache:/data

  user:
    container_name: user
    build:
      context: .
      dockerfile: social_network_dockerfile
    environment:
      - DB_HOST=social_network
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo_db
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
    depends_on:
      - db
    ports:
      - "8080:8080"

  message:
    container_name: message
    build:
      context: .
      dockerfile: social_network_dockerfile
    environment:
      - DB_HOST=social_network
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo_db
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
    depends_on:
      - db
    ports:
      - "8081:8080"
  
  post:
    container_name: post
    build:
      context: .
      dockerfile: social_network_dockerfile
    environment:
      - DB_HOST=social_network
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo_db
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
    depends_on:
      - db
    ports:
      - "8082:8080"

  social_network_gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: social_network_gateway_dockerfile
    environment:
      - DB_HOST=social_network
      - DB_PORT=5432
      - DB_LOGIN=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=user_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo_db
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
      - CACHE=cache:6379
      - USER_ADDRESS=http://user:8080
      - MES_ADDRESS=http://message:8080
      - POST_ADDRESS=http://post:8080
    ports:
      - 8888:8888

volumes:
  db_data:
  sn_cache:
  mongodb_data: